name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Change Permissions
      run: chmod -R 777 /home/joeun/workspace/HelloSpringBoot

    - name: Deploy to Server
      run: |
        cd /home/joeun/workspace/HelloSpringBoot
        
        # Run start.sh in the background and save PID
        nohup ./start.sh > /dev/null 2>&1 & echo $! > app.pid

        # Optionally, you can display the PID
        cat app.pid

        # Wait for the background process to finish
        wait
