name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Make Gradle Wrapper Executable
      run: chmod +x ./hello/gradlew

    - name: Build with Gradle
      run: ./hello/gradlew clean build

    - name: Run Java Application
      run: java -jar build/libs/hello-app.war
