name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: permission check
        run: chmod -R 777 .

      - name: Build with Gradle
        run: ./gradlew clean build

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "> 새로운 애플리케이션 배포"
          # cd $GITHUB_WORKSPACE/build/libs
          cd /home/joeun/workspace/HelloSpringBoot/build/libs
          
          # 서버 실행
          echo "> 서버 실행"
          nohup java -jar "hello-application.war" &
