name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: deploy to server
      run: ssh joeun@172.18.127.251 'cd /home/joeun/workspace/HelloSpringBoot && git pull && ./gradlew clean build && cd ./build/libs && java -jar hello-application.war'
