name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: change mod
      run: chmod -R 777 /home/joeun/workspace/HelloSpringBoot

    # - name: deploy to server
    #   run:  cd /home/joeun/workspace/HelloSpringBoot/build/libs && 
    #         nohup java -jar hello-application.war &
    - name: deploy to server
      run:  cd /home/joeun/workspace/HelloSpringBoot && 
            start.sh
            